config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  resources :contacts, only: [:new, :create] 
  post "/product/message" => "products#email_product", as: :email_product
   get "products/terms_and_conditions", :to => "products#terms_and_conditions"
   get "products/privacy_policy", :to => "products#privacy_policy"
  resources :products do
    resources :comments
    resources :reviews
    
  end

  
  devise_for :users
   get "users/products/terms_and_conditions", :to => "products#terms_and_conditions"
  root to: 'products#index'
   
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/cancel' => 'devise/registrations#cancel'
  end 
  resources :categories

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	
    extend FriendlyId
    friendly_id :category, use: :slugged

    resourcify
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
     @categories = Category.all
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
<%= button_to 'delete this product?', @category, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="ml-3">Categories</h3>

<% if has_role?(:admin) %>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

<% else %>
<p class="has text-center text-white ml-3 btn bg-danger"> Sorry! You don't have right to access this page. </p><br>
<%= link_to 'Back', products_path,class:" btn btn-primary ml-3 mb-5" %>
<% end %>

app/views/categories/new.html.erb
<div class="col-md-8 mt-5 mb-5">
<h1 class="mb-3">New Category</h1>

<%= render 'form', category: @category %>

<div class="btn btn-default">
<%= link_to 'Back', categories_path,class:" btn btn-primary mb-5" %>
</div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<%= button_to 'delete this product?', @category, method: :delete, data: { confirm: 'Are you sure?' } %>