config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  resources :contacts, only: [:new, :create] 
  post "/product/message" => "products#email_product", as: :email_product
   get "products/terms_and_conditions", :to => "products#terms_and_conditions"
   get "products/privacy_policy", :to => "products#privacy_policy"
  resources :products do
    resources :comments
    resources :reviews
    
  end

  
  devise_for :users
   get "users/products/terms_and_conditions", :to => "products#terms_and_conditions"
  root to: 'products#index'
   
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/cancel' => 'devise/registrations#cancel'
  end 
  resources :categories

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :reviews

  has_many_attached :images, dependent: :destroy

  validates_acceptance_of :terms_and_conditions
  validates :terms_and_conditions, acceptance: true
  validates :name, :description, :images, :address,
        :company_name, :telephone_number, :price, presence: true
  
  validates :name, uniqueness: { case_sensitive: false }
  
  
    
    def self.search_by(search_term)
      where("LOWER(name) LIKE :search_term OR LOWER(company_name) LIKE :search_term", search_term: "%#{search_term.downcase}%")
    end
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    resourcify
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :set_product, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show, :terms_and_conditions, :privacy_policy]


  # GET /products or /products.json
  def index
    @categories = Category.all    

    cate = params[:cate]

    if cate.present?
      @products = Product.where(:category_id => cate).paginate(:page => params[:page], per_page: 2).order('created_at desc')
     else
      @products = Kaminari.paginate_array(Product.first(10)).page(params[:page]).per(2)
    end
  
    if params[:search]
        @search_term = params[:search]
        @products= @products.search_by(@search_term)
    end
  end

  # GET /products/1 or /products/1.json
  def show
     @categories = Category.all 
  end

  # GET /products/new
  def new
    @product = current_user.products.build
    @categories = Category.all 
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all 
  end

  # POST /products or /products.json
 def create
    @product = current_user.products.build(product_params)
    @categories = Category.all   
 
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js   { render :nothing => true }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
      @categories = Category.all 
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :address, :price, :description, :company_name, :available_date, :telephone_number, :link, :category_id, :user_id, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
 <div class="container col-sm-3 mb-5 mt-5 mr-1">
  <div class="row has text-warning">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div style="background-color: #000075;">
  <%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <% if @product.errors.any? %>
      <div id="error_explanation", class="btn btn-sm btn-danger mt-3 mb-3">
       <h2><%= pluralize(product.errors.count, "Error") %>
    prevented this product from being saved:</h2>
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="has text-center">
    <h6 class="h4 font-weight-normal text-muted has text-center">Please fill all the fields with this<div class="has text-warning">*</div></h6></div>
    
    <div class="pl-1 pr-1">
    <%= f.label :name %> 
    <div class="field">
    <%= f.text_field :name, maxlength: 100, placeholder: 'Product name', class:'form-control',required: true, autofocus: true, minlength: 100 %><br>
    </div>  
    
    <%= f.label :address %>  <i class="text-white">( You can type number/name of the road , Sector, House number/name )</i>
    <div class="field">
    <%= f.text_field :address, maxlength: 100, placeholder: 'Fill in here ', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
    </div>


    <%= f.label :company_name %>
      <div class="field">
        <%= f.text_field :company_name, maxlength: 100, placeholder: 'Company name', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
      </div> 
     
    
    <%= f.label :telephone_number %>
      <div class="field">
        <%= f.text_field :telephone_number, maxlength: 100, placeholder: 'telephone', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
      </div> 


    <%= f.label :Website_link %> <i class="text-white">( EXAMPLE: http: //www.website.com)</i>
      <div class="field">
        <%= f.text_field :link, maxlength: 100, placeholder: 'leave it blank if you dont have one.', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
      </div> 

      
    <%= f.label :description %>
      <div class="field">
           <%= f.text_area :description, placeholder: 'Add everything your clients needs to know!' , class:'form-control',required: true, autofocus: true,autofocus: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %><br>
      </div>

    
    <%= f.label :price %> <i></i>
      <div class="field">    <%= f.text_field :price, maxlength: 100, placeholder: 'Price', class:'form-control',required: true, autofocus: true, autocomplete: "off", minlength: 100 %><br>
      </div>


    <%= f.label :category %>
       <div class="field has text-dark">
        <%= f.select :category_id, Category.all.map {|c| [c.category, c.id]}, required: true, autofocus: true, minlength: 100 %><br>
      </div>     
    
      
      <div class="field mt-5">
          <div class="control">
            <%= f.input :images, as: :file, hint: '  Each image uploaded must be less than 2 megabytes', input_html: { multiple: true, direct_upload: true }, label: false, wrapper: false %>
          </div>
      </div>

    <br>
        <div class="text-center">
          <%= f.submit "Save Product", class: "btn btn-success mb-5" %>
          <%= link_to "Back", products_path, class:" btn btn-primary mb-2 ml-5 mb-5" %>
        <div class="checkbox">
        <label>
      <input type="checkbox" check="check" value="remember-me"> 
      By creating new product you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>
    </label></div>
     </div>
<% end %>
    </div>
</div></div>
  </div>
</div> 

app/views/products/_product.html.erb
<div style="padding-top: 10px;">
<div class="card-image pl-4">
    <figure class="image is-square">
    	<div>
        <div class="card"> 
          <div style="background-color: #000075; border: 1px solid #000075;">
      <%=link_to image_tag(product.images.first.variant(resize: "250x250!>")), product %>
      <!-- </div> -->
 
    <h4 class="pt0 title is-5 text-center"><%=link_to product.name, product, class: "text-warning"%></h4>
    
    <div class="media">
      
      <div class="media-content">
        <strong><p style="padding-left: 20px;" class="has-text-weight-bold mb0 has text-white">Posted by: <%= product.company_name %></p></strong>
       </div>
      </div>
    </div></div>
     </div>
    </figure>
</div></div>

app/views/products/edit.html.erb
<h2 class="has text-center mt-5">Editing Product</h2>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<section class="hero hero-normal">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All Categories</span> 
                        </div>
                        <div class="mr-md-12">
       
       
        <ul class="list-group">

        <% @categories.each do |category| %>
 
         <li class="row">
          <%= link_to category.category, products_path(:cate => category.id), class: "ml-2" %>
         <div style="margin-left:auto">
         <span class="badge badge-success badge-pill mr-3"><%= category.products.count%></span></div>
         </li>  
        <% end %>
        </ul>
        </div>
        </div></div></div> 
        </div></section>


<!-- Hero Section Begin -->
    <section class="hero">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                </div>
                <div class="col-lg-9">
                    <div class="hero__item set-bg" data-setbg="/assets/hero/banner.jpg">
                        <div class="hero__text">
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<!-- Hero Section Ends -->    

<!-- Categories Section Begin -->
    <div class="container"><%= paginate @products %></div>
    <%= link_to_prev_page @products, 'Previous Page' %>
<%= link_to_next_page @products, 'Next Page' %>
    <section class="categories">
        <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Most Accessed Products</h2>
                    </div>
                </div>
            </div>
        <div class="container">
            <div class="row">
                <div class="categories__slider owl-carousel">
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/assets/categories/cat-1.jpg">
                            <h5><a href="#">Fresh Fruit</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/assets/categories/cat-2.jpg">
                            <h5><a href="#">Dried Fruit</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/assets/categories/cat-3.jpg">
                            <h5><a href="#">Vegetables</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="/assets/categories/loga.jpg">
                            <h5><a href="#">Clothes and shoes</a></h5>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="categories__item set-bg" >
                            <%= link_to image_tag('logo.png', width: 40, class: "img-fluid"), '/'%> 
                            <h5><a href="#">Test</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Categories Section End -->

    <!-- Featured Section Begin -->
    <section class="featured spad">
         <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>All Products</h2>
                    </div>
                </div>
            </div>
    <div class="container">
        <div class="row ml-5">
  <div class="row">
  <div class="row mb-3 pt-4 pb-4">
  <% @products.each do |product| %>
   <div class="row ">
      <div style="width:25px;">
      </div>
   </div>
  <div class="row pl-4">
    <%= render product, product: product %>
  </div>
  <% end %>
  </div></div></div>
   <%= paginate @products %>             
    </section>
    
</body>
 
 <div class="mb-5 pb-5 pl-5 ml-5">
  </div> </div></div></section>

app/views/products/new.html.erb
<div class="section-title">
	<div style="padding-right: 10%;">
<h2 class="title is-3 text-center">New Product</h2></div>
</div>
<%= render 'form', product: @product %>

app/views/products/search.html.erb
<% if @products.any? %>

   <h3 class="ml-5 mb-1">Search Results</h3><hr />
   <%= render @products %>

<% else %>

  <p><h3 class="ml-5 mb-1">Search Results</h3><hr /> <a   class="has-text-center text-white mt-4 btn bg-danger ml-5"  >Sorry!!! Nothing matches your search</a></p>
  <p class="ml-5">Check if all words are spelled correctly</p>
  <p class="ml-5 mb-5">Or search again by category</p>
  <% end %>

app/views/products/show.html.erb
<section class="hero hero-normal">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All Categories</span> 
                        </div>
                        <div class="mr-md-12">
       
       
        <ul class="list-group">

        <% @categories.each do |category| %>
        
         <li class="row">
          <%= link_to category.category, products_path(:cate => category.id), class: "ml-2" %>
         <div style="margin-left:auto">
         <span class="badge badge-success badge-pill mr-3"><%= category.products.count%></span></div>
         </li>  
        <% end %>
        </ul>
        </div>
        </div></div></div> 
        </div></section> 

    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Notify.rw</h2>
                        <div class="breadcrumb__option">
                            <a href="/">Home</a>
                            <span>Adverts</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<%= yield (:body_class) %>


<div class="row pt-4 pb-3">
  <div class="container">
<div class="row is-multiline pt-4 mr-1">
  <div class="col-md-5">
      <div class="">
        <h4 class="lead ml-3">Category: <%= @product.category.category %></h4>       
          
        <div class="pl-4 mr-2">

        <h5 class="title is-1 ml-4">Product name: <%= @product.name %></h5>

        <strong><p class="col-md-4 ml-3 text-primary">Posted <%= time_ago_in_words(@product.created_at) %> ago</p></strong>
        
        <div class="border mb-3 pl-2">
        <strong class="border-bottom">Product description: </strong><%= sanitize markdown_to_html(@product.description) %>
        </div>
        </div>
      </div>
  </div>

  <div class="ml-4 mr-1 col-md-5">

      <div class="card row ml-auto mr-1">
        <h5 class="has text-white border-bottom"> Additional details: </h5>
        <span class="ml-5 mb-2 has text-warning"> 
          <div class="card-content pt-1 pb-2 lead">
          <div>Posted by: <%= @product.company_name %><a class="mt-1 mb-1 row text-right"></a>Address: <%= @product.address %><a class="mt-1 mb-1 row text-right"></a>Contacts: <%= @product.telephone_number %><a class="mt-1 row text-right"></a>Price: <%= @product.price %><a class="mt-1 row text-right"></a></a>Website link: <%= auto_link(@product.link) %></div></div>
        </span>
      </div>
  </div>
</div>
</div></div>

<div class="container has text-center">
<div class="row is-multiline pt-4 mb-5 ml-1 mr-3">

<div class="border ml-2">
        <div class="row pl-5 pt-1 pb-3 pr-3">
        <% @product.images.each do |image| %>
          <div class="column is-one-third ">

            <div style="height:25px;">
            </div>

              <div style="width:250px; height:180px;">
            <%= image_tag image.variant(resize: "320x160>") %>
          </div></div>
        <% end %>
</div></div>
      <iframe class="ml-lg-4 ml-2 mt-5" width="480" height="320" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDwPWqzUvZRkWVpkF52SD7uctfnLjDADdw&q=<%= @product.address.to_param %>" allowfullscreen></iframe>


      <% if product_author(@product) || has_role?(:admin) %>

       <div class="row col-md-6 mt-auto">
       <div class="pa3 mb4 pb-2 border-radius-3 mb-1 ml-3">  
        <p class="ml-3 mt-4 f6 pb1 has text-dark">Author actions:</p>
       
        <div class="card col-md-9 pt-3">
        <div class="button-group">
          <%= link_to "Edit product: #{@product.name}", edit_product_path(@product), class: "btn btn-sm btn btn-secondary mb-2 mr-1 " %>
          <%= link_to "Back", products_path, class: " btn btn-sm btn btn-primary mb-2 mr-1" %>
          <%= button_to 'delete this product?', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn btn-danger mb-3" %>
        </div></div>
      </div></div></div></div>
              <% end %>

    
      <div class="container">
        <div class="col-md-3 ml-3">
          <h3 class="">Reviews:</h3> 
          <%= render @product.reviews %></br>
          <div class="btn btn underline">
            <%= link_to "Add Review", new_product_review_path(@product), class:'card has text-warning has text-center mb-5' %>
          </div>
        </div>
      </div>
      

      <script>
        $('.review-rating').raty({
          readOnly: true,
          score: function() {
            return $(this).attr('data-score');
          },
          path: '/assets/'
        });
      </script>

      
      <div class="container">
        <section class="section comments">
      <div class="container">
        <h3 class="subtitle is-5 border-bottom has text-dark"><strong><%= @product.comments.count %></strong> Comments</h3>
        <%= render @product.comments %>
        <div class="comment-form">
            <hr />
            <h4 class="subtitle is-3 has text-dark has text-center">Leave a reply</h4>
             <%= render 'comments/form' %>
        </div>
      </div>
</section></div>
<% if user_signed_in? %>
    
    <% else %>
    <p>To comment you need to <%= link_to 'login', new_user_session_path %>. Don't 
      have an account? <%= link_to 'Sign up', new_user_registration_path %> for one. Thanks!</p>
    <% end %>