config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  resources :contacts, only: [:new, :create] 
  post "/product/message" => "products#email_product", as: :email_product
   get "products/terms_and_conditions", :to => "products#terms_and_conditions"
   get "products/privacy_policy", :to => "products#privacy_policy"
  resources :products do
    resources :comments
    resources :reviews
    
  end

  
  devise_for :users
   get "users/products/terms_and_conditions", :to => "products#terms_and_conditions"
  root to: 'products#index'
   
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/cancel' => 'devise/registrations#cancel'
  end 
  resources :categories

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController 
  before_action :find_product
  before_action :find_review, only: [:edit, :update, :destroy]

    def show
       @product = Product.friendly.find(params[:product_id])
       @review = @product.reviews.friendly.find(params[:id])
       @review.destroy
       redirect_to product_path(@product)
       @reviews = Review.where(product_id: @product.id).order("created_at DESC")
    end

	def new
	   @review = Review.new
	end

	def create
	   @review = Review.new(review_params)
	   @review.product_id = @product.id
	   @review.user_id = current_user.id

	   if @review.save
	   	redirect_to product_path(@product)
	   else
	   	render 'new'
	   end
	end

	def edit
	end

	def update
	   if @review.update(review_params)
	  	redirect_to product_path(@product)
	   else
	   	render 'edit'
	   end
	end

	def destroy
	   @review.destroy
	   redirect_to product_path(@product)
	end

	private

	  def review_params
		params.require(:review).permit(:rating, :comment)
	  end

	  def find_product
	   @product = Product.friendly.find(params[:product_id])
	  end

	  def find_review
	   @review = Review.friendly.find(params[:id])
	  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@product, @product.reviews.build]) do |f| %>
<div id="rating-form">
<label>Rating</label>
</div>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>


<script>
	$('#rating-form').raty({
	    path: '/assets/',
	    scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<div class="reviews">
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>
</div>


<% if user_signed_in? %>

  <% if review.user_id == current_user.id %>
  
  <%= link_to "Edit", edit_product_review_path(review.product, review) %>
  <%= link_to "Delete", product_review_path(review.product, review), method: :delete, data: {confirm: "Are you sure?"} %>

  <% end %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@product, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %> 

app/views/reviews/new.html.erb
<h3>New Review</h3>

<%= render 'form' %>

<%= link_to 'Back', product_path(@product) %>